// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Rbesselk
double Rbesselk(double x, double v);
RcppExport SEXP _libmatern_Rbesselk(SEXP xSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(Rbesselk(x, v));
    return rcpp_result_gen;
END_RCPP
}
// Rbesselk_dv
double Rbesselk_dv(double x, double v);
RcppExport SEXP _libmatern_Rbesselk_dv(SEXP xSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(Rbesselk_dv(x, v));
    return rcpp_result_gen;
END_RCPP
}
// Rbesselk_dx
double Rbesselk_dx(double x, double v);
RcppExport SEXP _libmatern_Rbesselk_dx(SEXP xSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(Rbesselk_dx(x, v));
    return rcpp_result_gen;
END_RCPP
}
// Rmatern
double Rmatern(double t, double sig, double rho, double nu);
RcppExport SEXP _libmatern_Rmatern(SEXP tSEXP, SEXP sigSEXP, SEXP rhoSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type sig(sigSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(Rmatern(t, sig, rho, nu));
    return rcpp_result_gen;
END_RCPP
}
// Rmatern_dsig
double Rmatern_dsig(double t, double sig, double rho, double nu);
RcppExport SEXP _libmatern_Rmatern_dsig(SEXP tSEXP, SEXP sigSEXP, SEXP rhoSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type sig(sigSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(Rmatern_dsig(t, sig, rho, nu));
    return rcpp_result_gen;
END_RCPP
}
// Rmatern_drho
double Rmatern_drho(double t, double sig, double rho, double nu);
RcppExport SEXP _libmatern_Rmatern_drho(SEXP tSEXP, SEXP sigSEXP, SEXP rhoSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type sig(sigSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(Rmatern_drho(t, sig, rho, nu));
    return rcpp_result_gen;
END_RCPP
}
// Rmatern_dnu
double Rmatern_dnu(double t, double sig, double rho, double nu);
RcppExport SEXP _libmatern_Rmatern_dnu(SEXP tSEXP, SEXP sigSEXP, SEXP rhoSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type sig(sigSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(Rmatern_dnu(t, sig, rho, nu));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_libmatern_Rbesselk", (DL_FUNC) &_libmatern_Rbesselk, 2},
    {"_libmatern_Rbesselk_dv", (DL_FUNC) &_libmatern_Rbesselk_dv, 2},
    {"_libmatern_Rbesselk_dx", (DL_FUNC) &_libmatern_Rbesselk_dx, 2},
    {"_libmatern_Rmatern", (DL_FUNC) &_libmatern_Rmatern, 4},
    {"_libmatern_Rmatern_dsig", (DL_FUNC) &_libmatern_Rmatern_dsig, 4},
    {"_libmatern_Rmatern_drho", (DL_FUNC) &_libmatern_Rmatern_drho, 4},
    {"_libmatern_Rmatern_dnu", (DL_FUNC) &_libmatern_Rmatern_dnu, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_libmatern(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
