// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cbesselK
double cbesselK(double x, double v);
RcppExport SEXP _libmatern_cbesselK(SEXP xSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(cbesselK(x, v));
    return rcpp_result_gen;
END_RCPP
}
// cbesselK_dv
double cbesselK_dv(double x, double v);
RcppExport SEXP _libmatern_cbesselK_dv(SEXP xSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(cbesselK_dv(x, v));
    return rcpp_result_gen;
END_RCPP
}
// cbesselK_dx
double cbesselK_dx(double x, double v);
RcppExport SEXP _libmatern_cbesselK_dx(SEXP xSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(cbesselK_dx(x, v));
    return rcpp_result_gen;
END_RCPP
}
// cmatern
double cmatern(double t, double sig, double rho, double nu);
RcppExport SEXP _libmatern_cmatern(SEXP tSEXP, SEXP sigSEXP, SEXP rhoSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type sig(sigSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(cmatern(t, sig, rho, nu));
    return rcpp_result_gen;
END_RCPP
}
// cmatern_dsig
double cmatern_dsig(double t, double sig, double rho, double nu);
RcppExport SEXP _libmatern_cmatern_dsig(SEXP tSEXP, SEXP sigSEXP, SEXP rhoSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type sig(sigSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(cmatern_dsig(t, sig, rho, nu));
    return rcpp_result_gen;
END_RCPP
}
// cmatern_drho
double cmatern_drho(double t, double sig, double rho, double nu);
RcppExport SEXP _libmatern_cmatern_drho(SEXP tSEXP, SEXP sigSEXP, SEXP rhoSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type sig(sigSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(cmatern_drho(t, sig, rho, nu));
    return rcpp_result_gen;
END_RCPP
}
// cmatern_dnu
double cmatern_dnu(double t, double sig, double rho, double nu);
RcppExport SEXP _libmatern_cmatern_dnu(SEXP tSEXP, SEXP sigSEXP, SEXP rhoSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type sig(sigSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(cmatern_dnu(t, sig, rho, nu));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_libmatern_cbesselK", (DL_FUNC) &_libmatern_cbesselK, 2},
    {"_libmatern_cbesselK_dv", (DL_FUNC) &_libmatern_cbesselK_dv, 2},
    {"_libmatern_cbesselK_dx", (DL_FUNC) &_libmatern_cbesselK_dx, 2},
    {"_libmatern_cmatern", (DL_FUNC) &_libmatern_cmatern, 4},
    {"_libmatern_cmatern_dsig", (DL_FUNC) &_libmatern_cmatern_dsig, 4},
    {"_libmatern_cmatern_drho", (DL_FUNC) &_libmatern_cmatern_drho, 4},
    {"_libmatern_cmatern_dnu", (DL_FUNC) &_libmatern_cmatern_dnu, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_libmatern(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
