# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rbesselk <- function(x, v) {
    .Call('_libmatern_Rbesselk', PACKAGE = 'libmatern', x, v)
}

Rbesselk_dv <- function(x, v) {
    .Call('_libmatern_Rbesselk_dv', PACKAGE = 'libmatern', x, v)
}

Rbesselk_dx <- function(x, v) {
    .Call('_libmatern_Rbesselk_dx', PACKAGE = 'libmatern', x, v)
}

Rmatern <- function(t, sig, rho, nu) {
    .Call('_libmatern_Rmatern', PACKAGE = 'libmatern', t, sig, rho, nu)
}

Rmatern_dsig <- function(t, sig, rho, nu) {
    .Call('_libmatern_Rmatern_dsig', PACKAGE = 'libmatern', t, sig, rho, nu)
}

Rmatern_drho <- function(t, sig, rho, nu) {
    .Call('_libmatern_Rmatern_drho', PACKAGE = 'libmatern', t, sig, rho, nu)
}

Rmatern_dnu <- function(t, sig, rho, nu) {
    .Call('_libmatern_Rmatern_dnu', PACKAGE = 'libmatern', t, sig, rho, nu)
}

