# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cbesselK <- function(x, v) {
    .Call('_libmatern_cbesselK', PACKAGE = 'libmatern', x, v)
}

cbesselK_vec <- function(x_list, v) {
    .Call('_libmatern_cbesselK_vec', PACKAGE = 'libmatern', x_list, v)
}

cbesselK_dv <- function(x, v) {
    .Call('_libmatern_cbesselK_dv', PACKAGE = 'libmatern', x, v)
}

cbesselK_dx <- function(x, v) {
    .Call('_libmatern_cbesselK_dx', PACKAGE = 'libmatern', x, v)
}

cmatern <- function(t, sig, rho, nu) {
    .Call('_libmatern_cmatern', PACKAGE = 'libmatern', t, sig, rho, nu)
}

cmatern_dsig <- function(t, sig, rho, nu) {
    .Call('_libmatern_cmatern_dsig', PACKAGE = 'libmatern', t, sig, rho, nu)
}

cmatern_drho <- function(t, sig, rho, nu) {
    .Call('_libmatern_cmatern_drho', PACKAGE = 'libmatern', t, sig, rho, nu)
}

cmatern_dnu <- function(t, sig, rho, nu) {
    .Call('_libmatern_cmatern_dnu', PACKAGE = 'libmatern', t, sig, rho, nu)
}

