# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The modified second-kind Bessel function K_v(x)
#'
#' @param x the argument
#' @param v the order
#' @return the evaluation K_v(x)
NULL

#' The derivative of the modified second-kind Bessel function K_v(x) with respect
NULL

#' The derivative of the modified second-kind Bessel function K_v(x) with respect
NULL

.cbesselK_bufX <- function(x_list, v) {
    .Call('_libmatern_cbesselK_bufX', PACKAGE = 'libmatern', x_list, v)
}

.cbesselK_bufV <- function(x, v_list) {
    .Call('_libmatern_cbesselK_bufV', PACKAGE = 'libmatern', x, v_list)
}

.cbesselK_bufBoth <- function(x_list, v_list) {
    .Call('_libmatern_cbesselK_bufBoth', PACKAGE = 'libmatern', x_list, v_list)
}

.cbesselK_scalar <- function(x, v) {
    .Call('_libmatern_cbesselK_scalar', PACKAGE = 'libmatern', x, v)
}

#'
#' @param x the argument
#' @param v the order
#' @return the evaluation (d/dv) K_v(x)
cbesselK_dv <- function(x, v) {
    .Call('_libmatern_cbesselK_dv', PACKAGE = 'libmatern', x, v)
}

#'
#' @param x the argument
#' @param v the order
#' @return the evaluation (d/dx) K_v(x)
cbesselK_dx <- function(x, v) {
    .Call('_libmatern_cbesselK_dx', PACKAGE = 'libmatern', x, v)
}

#' The Matern covariance function as paramterized by [wikipedia](https://en.wikipedia.org/wiki/Mat%C3%A9rn_covariance_function).
#'
#' @param t the distance/argument
#' @param sig the marginal standard deviation
#' @param rho the range parameter
#' @param nu  the smoothness parameter
#' @return the Matern covariance function with parameters (sig, rho, nu)
#' evaluated at distance t.
cmatern <- function(t, sig, rho, nu) {
    .Call('_libmatern_cmatern', PACKAGE = 'libmatern', t, sig, rho, nu)
}

#' The derivative of the Matern covariance function with respect to sigma.
#'
#' @param t the distance/argument
#' @param sig the marginal standard deviation
#' @param rho the range parameter
#' @param nu  the smoothness parameter
#' @return the derivative of the Matern covariance function with respect to
#' sigma with parameters (sig, rho, nu) ' evaluated at distance t.
cmatern_dsig <- function(t, sig, rho, nu) {
    .Call('_libmatern_cmatern_dsig', PACKAGE = 'libmatern', t, sig, rho, nu)
}

#' The derivative of the Matern covariance function with respect to rho.
#'
#' @param t the distance/argument
#' @param sig the marginal standard deviation
#' @param rho the range parameter
#' @param nu  the smoothness parameter
#' @return the derivative of the Matern covariance function with respect to
#' rho with parameters (sig, rho, nu) ' evaluated at distance t.
cmatern_drho <- function(t, sig, rho, nu) {
    .Call('_libmatern_cmatern_drho', PACKAGE = 'libmatern', t, sig, rho, nu)
}

#' The derivative of the Matern covariance function with respect to nu.
#'
#' @param t the distance/argument
#' @param sig the marginal standard deviation
#' @param rho the range parameter
#' @param nu  the smoothness parameter
#' @return the derivative of the Matern covariance function with respect to
#' nu with parameters (sig, rho, nu) ' evaluated at distance t.
cmatern_dnu <- function(t, sig, rho, nu) {
    .Call('_libmatern_cmatern_dnu', PACKAGE = 'libmatern', t, sig, rho, nu)
}

