name: LinuxRPackageTest

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone R package
      run: |
        pwd
        cd test
        Rscript test_package.R
