name: LinuxRPackageTest

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: r-lib/actions/setup-r@v2
    - name: Clone R package
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ls
        pwd
        cd test
        Rscript test_package.R
