name: LinuxRPackageTest

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: r-lib/actions/setup-r@v2
    - name: Clone R package
      run: |
        cd test
        Rscript test_package.R
