name: LinuxRPackageTest

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: r-lib/actions/setup-r@v2
    - name: Clone R package
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      run: |
        #sudo apt-get install -y libharfbuzz-dev libfribidi-dev libcurl4-openssl-dev
        Rscript -e 'install.packages("remotes")' \
                -e 'remotes::install_github("cgeoga/libmatern", auth_token = Sys.getenv("GITHUB_PAT"))' \
                -e 'library("libmatern")' \
                -e 'besselk(1.1, 2.1, 0)'
        #R -e 'devtools::install_github("cgeoga/libmatern")'
        #R -e 'library("libmatern")'
        #R -e 'besselk(1.1, 2.1, 0)'
