name: C Mac

on:
  workflow_dispatch:

jobs:
  build:
  
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install enzyme
      run: |
        brew update
        brew install enzyme

    - name: Compile .dylib with Enzyme
      working-directory: C_src
      run: |
        #find /opt/homebrew/Cellar -name "ClangEnzyme-*"
        /opt/homebrew/Cellar/llvm/18.1.8/bin/clang libmatern.c -fplugin=/opt/homebrew/Cellar/enzyme/0.0.148/lib/ClangEnzyme-18.dylib -O3 -lm -Wall -pedantic -shared -fPIC -o libmatern.dylib

    - name: Run tests
      working-directory: C_src
      run: |
        clang test_script.c -o test_script -L. -Wl,-rpath,/Users/runner/work/besselk_enzyme/besselk_enzyme/C_src libmatern.dylib #REPLACES make test
        ./test_script
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: libmatern.dylib
        path: C_src/libmatern.dylib
      
