name: MacPackageLocalTest

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: r-lib/actions/setup-r@v2
    - name: Test R package
      run: |
        R -e "install.packages('remotes'); remotes::install_local('./libmatern'); libmatern::besselk(1.1, 2.1, 0)"
       
