name: MacRPackage

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: r-lib/actions/setup-r@v2
    - name: Clone R package
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
      run: |
        R
        install.packages("devtools")
        devtools::install_github("cgeoga/libmatern")
        library("libmatern")
        besselk(1.1, 2.1, 0)
