name: MacRPackage

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: r-lib/actions/setup-r@v2
    - name: Clone R package
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
      run: |
        R -e 'install.packages("devtools")'
        R -e 'devtools::install_github("cgeoga/libmatern", auth_token = Sys.getenv("GITHUB_PAT"))'
        #R -e 'Sys.setenv(GITHUB_PAT = Sys.getenv("GITHUB_PAT"))'
        #R -e 'devtools::install_github("cgeoga/libmatern")'
        R -e 'library("libmatern")'
        R -e 'besselk(1.1, 2.1, 0)'
