name: MacRPackage

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: r-lib/actions/setup-r@v2
    - name: Clone R package
      run: |
        R -e 'install.packages("devtools")'
        R -e 'devtools::install_github("cgeoga/libmatern")'
        R -e 'library("libmatern")'
        R -e 'besselk(1.1, 2.1, 0)'
