name: MacRPackage

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: r-lib/actions/setup-r@v2
    - name: Clone R package
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      run: |
        R -e "install.packages('remotes');remotes::install_github('cgeoga/libmatern', auth_token = Sys.getenv('GITHUB_PAT'));library('libmatern');besselk(1.1, 2.1, 0)"
